fix qmk configuration
jporter-dev/keymaps pull request #3
Opened 2023-06-09 08:05 UTC by worms19

2023-06-09 08:05 UTC, worms19 commented
i made a fix for qmk version 1.1.2

2023-06-12 18:08 UTC, jporter-dev requested changes
Thanks for the PR! I added a couple of comments. I'll see if I can get QMK installed again and build it too.

2023-06-12 18:08 UTC, jporter-dev commented on qmk/keymap.c
> +        KC_NO, KC_GRAVE, KC_NO, KC_NO, KC_NO, KC_NO,        /* */   KC_MINS, KC_EQUAL, KC_LBRC, KC_RBRC, KC_SLASH, KC_NO,
`KC_SLASH` should be `KC_BSLS` as it is replacing `KC_BSLASH`

2023-06-12 18:08 UTC, jporter-dev commented on qmk/config.h
> -#define IGNORE_MOD_TAP_INTERRUPT
Why was this removed? Is there a replacement for `IGNORE_MOD_TAP_INTERRUPT` in the new version?

2023-09-27 14:22 UTC, jporter-dev commented
The files in this repo were rather old. Removed them and [this repo](https://github.com/jporter-dev/zmk-config) should be used and is linked in the README.

2023-09-27 14:22 UTC, closed without merging